name: Autograding Tests

on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Check file structure
      run: |
        if [ ! -d "geo" ]; then
          echo "geo folder missing"
          exit 1
        fi
        if [ ! -f "geo/__init__.py" ]; then
          echo "__init__.py missing"
          exit 1
        fi
        if [ ! -f "geo/utils.py" ]; then
          echo "utils.py missing"
          exit 1
        fi
        if [ ! -f "tester.py" ]; then
          echo "tester.py missing"
          exit 1
        fi

    - name: Run Autograding Test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: geometry-test
        setup-command: ""
        command: python tester.py
